# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :setBuildBasedOnInternalTesting do
    version = google_play_track_version_codes(
      json_key_data: ENV["GOOGLE_API_KEY"],
      track: "internal",
      package_name: "com.owenbean.reciperoots"
    )

    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/
    s = File.read(path)
    s[re, 1] = (version[0] + 1).to_s
    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  desc "Deploy a new version to the Google Play"
  lane :deployInternalTesting do
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      package_name: "com.owenbean.reciperoots",
      json_key_data: ENV["GOOGLE_API_KEY"],
      track: "internal",
      release_status: 'draft'
    )
  end
end
